name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - deployment
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deployment

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
          
      - name: Clean and Install
        run: |
          rm -rf build dist
          pnpm install --frozen-lockfile
        
      - name: Build
        run: pnpm run build
        env:
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
          VITE_WEATHER_API_BASE_URL: ${{ secrets.VITE_WEATHER_API_BASE_URL }}

      - name: Check build size
        run: |
          BUILD_SIZE=$(du -sb build | cut -f1)
          if [ $BUILD_SIZE -gt 262144000 ]; then
            echo "Build size ($BUILD_SIZE bytes) exceeds limit (262144000 bytes)"
            exit 1
          fi
          echo "Build size: $BUILD_SIZE bytes"

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "build"
          app_artifact_location: "build"
          skip_app_build: true
