name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - deployment
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deployment

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'
  
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      
      # Setup PNPM with proper caching
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          
      # Clear caches and install dependencies
      - name: Clean and Install
        run: |
          pnpm store prune
          pnpm install --frozen-lockfile --prefer-offline
          
      # Add build size check
      - name: Check bundle size
        run: |
          echo "Analyzing build size..."
          du -sh ./node_modules
          du -sh ./*
          
      # Optimize build process
      - name: Build
        run: |
          pnpm run build
          echo "Build size:"
          du -sh dist/
        env:
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
          VITE_WEATHER_API_BASE_URL: ${{ secrets.VITE_WEATHER_API_BASE_URL }}
          VITE_STORAGE_URL: ${{ secrets.VITE_STORAGE_URL }}
          NODE_ENV: production
          
      # Add size check before deployment
      - name: Verify build size
        run: |
          BUILD_SIZE=$(du -sb "dist" | cut -f1)
          if [ $BUILD_SIZE -gt 262144000 ]; then
            echo "Build size ($BUILD_SIZE bytes) exceeds Azure Static Web Apps limit"
            exit 1
          fi
          echo "Build size ($BUILD_SIZE bytes) is within limits"

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
          app_artifact_location: "dist"
          skip_app_build: true