name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - deployment
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deployment

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'
  
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      
      # Setup PNPM with specific version
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          
      # Force regenerate lockfile and install dependencies
      - name: Install Dependencies
        run: |
          rm -f pnpm-lock.yaml
          pnpm install --no-frozen-lockfile
          pnpm install --frozen-lockfile
          
      # Add build size check
      - name: Build
        run: |
          pnpm run build
          node scripts/check-build-size.js
        env:
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
          VITE_WEATHER_API_BASE_URL: ${{ secrets.VITE_WEATHER_API_BASE_URL }}
          VITE_STORAGE_URL: ${{ secrets.VITE_STORAGE_URL }}
          NODE_ENV: production

      - name: Deploy
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
          app_artifact_location: "dist"
          skip_app_build: true

      - name: Close Pull Request
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"